### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Satakshi20** [Codefamily-developer/Codefamily_Website#2]
I would like to work on this issue. Please assign me this issue

**Comment by Abhishek-Vaidya** [comment]
I can solve this issue can you assign me this?

**Comment by Codefamily1** [comment]
> I would like to work on this issue. Please assign me this issue

@Satakshi20 Go ahead

**Comment by Mr-krishn** [comment]
hey @Codefamily1 ,i can do this please assign this to me
