### ISSUE TITLE
Adding Dark Mode Toggle Button

### ISSUE THREAD

**Issue by sabhisharma-ise** [Codefamily-developer/Codefamily_Website#25]
![image](https://user-images.githubusercontent.com/100849696/212737264-563c9385-4454-4cf1-9088-90d7a4184e33.png)
- Adding a dark mode toggle button to the website so on clicking the same, the website will preview in a dark mode, and if toggled it'll go back to normal mode.

**Comment by Pratham-19** [comment]
HI can i work on this ?

**Comment by YashBawa** [comment]
Hello @sabhisharma-ise , 
I want to work on this issue. 
Please assign this issue to me.

**Comment by YashBawa** [comment]
@Codefamily1 should I start working on this issue ?
