### ISSUE TITLE
Make the Website Responsive

### ISSUE THREAD

**Issue by Codefamily1** [Codefamily-developer/Codefamily_Website#3]

**Comment by Sodium-Sharma** [comment]
hey @Codefamily1 i would like to contribute to this. Assign me.

**Comment by Codefamily1** [comment]
> hey @Codefamily1 i would like to contribute to this. Assign me.

@Sodium-Sharma Sure, Go ahead

**Comment by Sodium-Sharma** [comment]
@Codefamily1 the site is already responsive, but there are minor alignment issues on landing and about page in mobile view, I am going to fix that. But if you want anything else to be changed, you can mention that.
